services:
  db:
    image: postgres:17-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-db
    ports:
      - "6432:5432"
    # volumes:
    #   - ./apollo-dump.sql:/docker-entrypoint-initdb.d/apollo-dump.sql
    networks:
      - apollo
  
  db-test:
    image: postgres:17-alpine3.21
    container_name: db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-db-test
    ports:
      - "6433:5432"
    # volumes:
    #   - ./apollo-dump.sql:/docker-entrypoint-initdb.d/apollo-dump.sql
    networks:
      - apollo

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-dc
    container_name: apollo-api-dc
    ports:
      - "8080:8080"
      - "8085:5005" # Porta de depuração remota
    depends_on:
      - db
      - db-test
    volumes:
      - ..:/workspace
    networks:
      - apollo
  
networks:
  apollo:
    external: true
    driver: bridge