services:
  db:
    image: postgres:17-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app-db
    ports:
      - "6432:5432"
    # volumes:
    #   - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - apollo

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-dc
    container_name: app
    ports:
      - "9080:8080"
      - "6005:5005" # Porta de depuração remota
    depends_on:
      - db
    volumes:
      - ..:/workspace
    networks:
      - apollo
  
networks:
  apollo:
    external: true
    driver: bridge